site_name: goVirtualOffice Accelerator's Documentation
theme:
  name: readthedocs
nav:
  - Home: index.md
  - SimpleConnect: simpleconnect.md
  - BoostSync: boostsync.md
  - SuiteQL Chrome Extension: suiteql.md
